services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  postgres_data: